/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-08 04:39:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jspx extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Lindan/Documents/GitRepos/4413ZGroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MUGABookstore/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("jar:file:/C:/Users/Lindan/Documents/GitRepos/4413ZGroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MUGABookstore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583341034218L));
    _jspx_dependants.put("jar:file:/C:/Users/Lindan/Documents/GitRepos/4413ZGroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MUGABookstore/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153399482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
      out.write("<head>");
      out.write("<title>");
      out.write("MUGA Bookstore - Main Page");
      out.write("</title>");
      out.write("<link media=\"screen, print\" title=\"cse4413\" type=\"text/css\" href=\"resources/index.css\" rel=\"stylesheet\"/>");
      out.write("<link type=\"text/css\" href=\"resources/navigation.css\" rel=\"stylesheet\"/>");
      out.write("<link type=\"text/css\" href=\"resources/common.css\" rel=\"stylesheet\"/>");
      out.write("</head>");
      out.write("<body>");
      out.write("<section class=\"homeSection\">");
      out.write("<div id=\"navigationBar\">");
      out.write("<a class=\"leftNavigation\" href=\"" + (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null) + "\">");
      out.write("Home");
      out.write("</a>");
      out.write("<a class=\"leftNavigation\" href=\"" + (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/product-catalogue", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null) + "\">");
      out.write("Product Catalog");
      out.write("</a>");
      out.write("<a class=\"rightNavigation\" href=\"\">");
      out.write("Login/Register");
      out.write("</a>");
      out.write("<a class=\"rightNavigation\" href=\"" + (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/cart", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null) + "\">");
      out.write("Cart");
      out.write("</a>");
      out.write("</div>");
      out.write("<div id=\"mainpageHeaderDiv\">");
      out.write("<h1>");
      out.write("MUGA BOOKSTORE");
      out.write("</h1>");
      out.write("</div>");
      out.write("<div class=\"mainElements\" id=\"searchBar\">");
      out.write("<form method=\"POST\" action=\"searchQuery\">");
      out.write("<input placeholder=\"Search\" name=\"searchQuery\" id=\"searchQuery\" type=\"text\"/>");
      out.write("<button>");
      out.write("Search");
      out.write("</button>");
      out.write("</form>");
      out.write("</div>");
      out.write("<div class=\"mainElements\" id=\"news\">");
      out.write("MUGA Bookstore Grand Opening");
      out.write("</div>");
      out.write("<div id=\"featuredBooks\"/>");
      out.write("<hr/>");
      out.write("</section>");
      out.write("</body>");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
